# Generated by Django 6.1 on 2026-08-07 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('NOT STARTED', 'Not Started'), ('IN PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ON HOLD', 'On Hold')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=200)),
                ('module_description', models.TextField()),
                ('status', models.CharField(choices=[('NOT STARTED', 'Not Started'), ('IN PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ON HOLD', 'On Hold')], max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=200)),
                ('topic_description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('estimated_hours', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('TODO', 'Todo'), ('IN PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('assigned_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.module')),
            ],
        ),
    ]
